#!/usr/bin/env python3
"""Generate both editions' shared question definitions and the current math index."""
import argparse,json
from pathlib import Path
from make_inventory import tex
PAPER=Path(__file__).resolve().parents[1]
def key(n):return tuple(map(int,n.split('.')))
def render():
 d=json.loads((PAPER/'data/problem-statements.json').read_text())['entries']
 ledger=json.loads((PAPER/'data/frozen-candidate-ledger.json').read_text())['candidates']
 current=json.loads((PAPER/'data/current-assessment.json').read_text())
 rows=sorted([r for r in ledger if r['problem'] not in current['withdrawn_candidates']],key=lambda r:key(r['problem']))
 assert len(rows)==current['remaining_candidates']==45
 defs=['% Generated by scripts/render_editions.py from data/problem-statements.json.']
 for n,r in sorted(d.items(),key=lambda x:key(x[0])):
  for field,prefix in [('authors_tex','knauthor'),('question_tex','knquestion'),('scope_tex','knscope')]:
   s=r[field]
   if field=='scope_tex' and s:s=r'\noindent\emph{Scope.} '+s
   defs.append(r'\expandafter\def\csname '+prefix+'@'+n+r'\endcsname{'+s+'}')
 def label(n):return {'21.106':'subsec:concise','21.68':'subsec:semiabelian','20.108':'subsec:holomorph'}.get(n,'cand:'+n)
 idx=[r'''% Generated by scripts/render_editions.py.
\section{Index of results}\label{app:inventory}
This table indexes the 45 remaining candidate answers. It records the
covered subparts, without treating that count as a novelty or correctness
certificate. Each proof begins with the question and its author; the
scope qualifications and references to overlapping work appear alongside
it. The claim for 10.35 is withdrawn and contributes no entry here.
\small
\begin{longtable}{@{}p{0.09\textwidth}p{0.075\textwidth}>{\raggedright\arraybackslash}p{0.69\textwidth}r@{}}
\toprule Problem & Parts & Result & Page\\\midrule\endfirsthead
\toprule Problem & Parts & Result & Page\\\midrule\endhead
\bottomrule\endfoot
''']
 proofs=[r'''% Generated by scripts/render_editions.py; every proof source is shared.
\section{Candidate answers}\label{app:candidates}\label{sec:examples}
\input{shared/matrix-centralizer}
''']
 attrs={r['ledger_problem']:r['note_path'].removesuffix('.tex') for r in json.loads((PAPER/'reviews/v2-2026-09-19/comparison.json').read_text())['entries']}
 for r in rows:
  n=r['problem'];scope=r['covered_subparts'].split(';')[0]
  idx.append(f'{tex(n)} & {tex(scope)} & {d[n].get("result_tex",tex(r["result"]))} & \\pageref{{{label(n)}}} \\\\\n')
  stem='21-121a' if n=='21.121' else n.replace('.','-')
  proofs.append(r'\input{sections/candidates/'+stem+'}\n')
  # Two representative files already contain their own attribution input.
  if n in attrs and n not in {'21.106','21.68'}:proofs.append(r'\input{'+attrs[n]+'}\n')
 idx.append('\\end{longtable}\n\\normalsize\n')
 partials=[('20.100','partial:20.100',r'Torsion-free groups and certified $n=4,5,6,7$ cases; arbitrary $n$ remains open.'),('20.89/19.83','partial:engel',r'Characteristic zero and other specified classes; general positive characteristic remains open.'),('21.121(b)','partial:jordan',r'Soluble bounds and permanence; the general upper bound three remains open.'),('20.124','partial:rb',r'Infinite free rank; finite rank remains open.'),('17.118','partial:17.118',r'Sharp bounds for $p=2,3$ and class-dependent bounds; unrestricted $p\geq5$ remains open.'),('21.114','partial:21.114',r'A derived-length-three example; no unbounded family.'),('19.108','partial:19.108',r'Order $p^{10}$ with a sufficiently large abelian normal subgroup.'),('18.120','partial:18.120',r'The case of nilpotency class at most four.'),('6.47','partial:6.47',r'The case of nilpotency class at most two.')]
 idx.append(r'''\subsection*{Partial results}
These nine questions are not counted as additional complete answers;
21.121(a) already occurs above.
\small\begin{longtable}{@{}p{0.14\textwidth}>{\raggedright\arraybackslash}p{0.72\textwidth}r@{}}
\toprule Problem & Proved scope and remaining limitation & Page\\\midrule\endhead
\bottomrule\endfoot
''')
 for n,l,s in partials:idx.append(f'{n} & {s} & \\pageref{{{l}}} \\\\\n')
 idx.append('\\end{longtable}\n\\normalsize\n')
 idx.append(r'''\subsection*{Prior results and deductions}
Section~\ref{app:prior} separates the existing results, rediscoveries and
further deductions for 13.19, 17.34, 21.115, 16.60, 21.132, 21.42, 20.33,
20.8, 20.11, 19.9, 16.14 and 19.48, and the formulation issue in 12.69.
The already solved 19.63 criterion is credited within the proof for 19.62.
These entries do not increase the candidate count.
''')
 return {'data/problem-statements.tex':'\n'.join(defs)+'\n','editions/math-index.tex':''.join(idx),'editions/math-proofs.tex':''.join(proofs)}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args()
 for n,s in render().items():
  if a.check:assert (PAPER/n).read_text()==s,('stale generated edition file',n)
  else:(PAPER/n).write_text(s)
 print('PASS: 69 shared question records; 45 current candidates; partial/prior scopes.')
if __name__=='__main__':main()
